const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Flash,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet
	];
};
self.C3_JsPropNameTable = [
	{Tilemap: 0},
	{Janela: 0},
	{Solid: 0},
	{Suporte: 0},
	{Flash: 0},
	{Bau: 0},
	{Platform: 0},
	{caixa: 0},
	{porta: 0},
	{chave: 0},
	{bomba: 0},
	{ScrollTo: 0},
	{jogador: 0},
	{sensorsolidochão: 0},
	{Keyboard: 0},
	{direcao: 0},
	{Porco_patrulheiro: 0},
	{sensorpatrulheiro_direita: 0},
	{sensorpatrulheiro_esquerda: 0},
	{porco_canhao: 0},
	{canhao: 0},
	{sensorcanhao: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{bala: 0},
	{vida_hud: 0},
	{itens_hud: 0},
	{black_backgroundtext: 0},
	{jogadordialogo: 0},
	{SpriteFont: 0},
	{chefao: 0},
	{Audio: 0},
	{vidas: 0}
];

self.InstanceType = {
	Tilemap: class extends self.ITilemapInstance {},
	Janela: class extends self.ISpriteInstance {},
	Suporte: class extends self.ISpriteInstance {},
	Bau: class extends self.ISpriteInstance {},
	caixa: class extends self.ISpriteInstance {},
	porta: class extends self.ISpriteInstance {},
	jogador: class extends self.ISpriteInstance {},
	sensorsolidochão: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Porco_patrulheiro: class extends self.ISpriteInstance {},
	sensorpatrulheiro_direita: class extends self.ISpriteInstance {},
	sensorpatrulheiro_esquerda: class extends self.ISpriteInstance {},
	porco_canhao: class extends self.ISpriteInstance {},
	canhao: class extends self.ISpriteInstance {},
	sensorcanhao: class extends self.ISpriteInstance {},
	bala: class extends self.ISpriteInstance {},
	vida_hud: class extends self.ISpriteInstance {},
	itens_hud: class extends self.ISpriteInstance {},
	black_backgroundtext: class extends self.ISpriteInstance {},
	jogadordialogo: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	chave: class extends self.ISpriteInstance {},
	bomba: class extends self.ISpriteInstance {},
	chefao: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {}
}